### PR TITLE
No need for empty __init__.py in plugin dirs

### LINKED ISSUE #450: migrate.py should not create empty __init__.py's in collections
From slack:
> Collections do not require empty `__init__.py` files. Normally you would on Python 2, but the Ansible collection loader eliminates the need for them.

### PR DESCRIPTION
**Pull request by mkrizek**
Fixes #450

### CODE REVIEW

**Comment by bcoca** [comment]
holding off on this, till we verify the scope and if this actually creates issues on collections (other than extra files).

**Comment by webknjaz** [comment]
I checked that it was there since the initial commit. So it's not related to what I recall. I confused it with https://github.com/ansible-community/collection_migration/issues/80. It should be fine to merge this one.

**Comment by nitzmahone** [comment]
Yep, it's unnecessary for collections to function since `AnsibleCollectionLoader` implements its own implicit namespace packages (that also work on Python 2.7). The only reason you'd need those is for poking at collections with native Python 2.7 tools that aren't using our loader, which should be decreasingly likely over time.

**Comment by bcoca** [comment]
since this does not 'hurt' and does enable common python tools to keep working, going to close and let 'collection maintainers' decide to purge them at later date.

**Pull request closed without merging**
