### PR TITLE
community.crypto

### PR DESCRIPTION
**Pull request by gundalow**
As per [communities request](https://github.com/ansible/community/issues/444#issuecomment-591037367) create `community.crypto`.

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
Lots of mudules have `extends_documentation_fragment: files` - I assume this fragment will live in Ansible upstream. Is that properly handled when building documentation?

**Comment by gundalow** [comment]
> Lots of mudules have `extends_documentation_fragment: files` - I assume this fragment will live in Ansible upstream. Is that properly handled when building documentation?

Yup
The `migrate.py` process rewrite the other to be
`extends_documentation_fragment: community.crypto.acme` so all should be good

**Comment by MarkusTeufelberger** [comment]
Looks good to me too

shipit

**Comment by gundalow** [comment]
Rebased to include `parsing/__init__.py`

**Pull request merged**
