### PR TITLE
add ovirt scenarios

### PR DESCRIPTION
**Pull request by mnecas**
This PR adds to NWO ovirt.yml
@gundalow

### CODE REVIEW

**Comment by mnecas** [comment]
Sorry about that. I did not know it will break something.

**Comment by goneri** [comment]
The Pr actually fix a 

> Sorry about that. I did not know it will break something.

np :-)

**Comment by gundalow** [comment]
@mnecas @goneri Hi. the mass migration has happened. Where should I put the new collection repo? 
github.com/ansible-collections, or do you have your own GitHub org?

**Comment by mnecas** [comment]
@gundalow hi, we have our GitHub repo https://github.com/ovirt/ovirt-ansible-collection

**Pull request merged**
