### PR TITLE
[NWO] Remove cache plugins which are not needed for running a controller

### LINKED ISSUE #265: NWO: Remove excess cache plugins
We currently have the following cache plugins in base which implement caching to a file on the filesystem:

- jsonfile.py
- pickle.py
- yaml.py

None of these are the default (memory is).  It feels like we should either move all of them out of base as they aren't selectable via a dedicated commandline arg and it's definitely possible to use ansible without them or to keep at most one of them and justify it as "We have one supported plugin for caching which doesn't hold everything in memory".

### PR DESCRIPTION
**Pull request by abadger**
Fixes #265

See justification in #265.

### CODE REVIEW

**Comment by jctanner** [comment]
@abadger please re-add the files to community.general or migrate.py will just leave them in base.

**Comment by abadger** [comment]
@jctanner has that changed?  When we last talked about this, everything unlisted in the nwo scenario was supposed to get put into community.general.  If that has never been the case, I'll have to rewrite all of the scripts that were checking against the scenario yaml file again.

**Comment by abadger** [comment]
These are the bookends of the conversation I'm talking about:

* https://ansible.slack.com/archives/GA8CZT6JF/p1580492965070300
* https://ansible.slack.com/archives/GA8CZT6JF/p1580493259075900

**Comment by jctanner** [comment]
@abadger yes, it's changed slightly. When I initially ran generate_nwo.py, it took care of creating community.general with all the leftovers, so nobody had to worry about creating it themselves. Now that we're at a stable state, lines removed from one spec file which are intended to end up in community.general need to be explicitly put there. I have an update_nwo.py script that will help make sure nothing gets missed, but it's not something that will get run on every commit.

**Comment by abadger** [comment]
Done

**Pull request merged**
